// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package saver is a generated GoMock package.
package saver

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	do "github.com/yuelin-peng/dbsavergo/domain/saver/do"
)

// MockDBSaver is a mock of DBSaver interface.
type MockDBSaver struct {
	ctrl     *gomock.Controller
	recorder *MockDBSaverMockRecorder
}

// MockDBSaverMockRecorder is the mock recorder for MockDBSaver.
type MockDBSaverMockRecorder struct {
	mock *MockDBSaver
}

// NewMockDBSaver creates a new mock instance.
func NewMockDBSaver(ctrl *gomock.Controller) *MockDBSaver {
	mock := &MockDBSaver{ctrl: ctrl}
	mock.recorder = &MockDBSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBSaver) EXPECT() *MockDBSaverMockRecorder {
	return m.recorder
}

// Eliminate mocks base method.
func (m *MockDBSaver) Eliminate(ctx context.Context, order *do.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Eliminate", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Eliminate indicates an expected call of Eliminate.
func (mr *MockDBSaverMockRecorder) Eliminate(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Eliminate", reflect.TypeOf((*MockDBSaver)(nil).Eliminate), ctx, order)
}

// Query mocks base method.
func (m *MockDBSaver) Query(ctx context.Context, orderNO string) (*do.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, orderNO)
	ret0, _ := ret[0].(*do.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockDBSaverMockRecorder) Query(ctx, orderNO interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockDBSaver)(nil).Query), ctx, orderNO)
}

// Save mocks base method.
func (m *MockDBSaver) Save(ctx context.Context, order *do.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDBSaverMockRecorder) Save(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDBSaver)(nil).Save), ctx, order)
}
