// Code generated by Kitex v0.1.4. DO NOT EDIT.

package dbsaverservice

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"workspace/dbsavergo/kitex_gen/db_saver_service"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SaveOrder(ctx context.Context, req *db_saver_service.SaveOrderRequest, callOptions ...callopt.Option) (r *db_saver_service.SaveOrderResponse, err error)
	QueryOrder(ctx context.Context, req *db_saver_service.QueryOrderRequest, callOptions ...callopt.Option) (r *db_saver_service.QueryOrderResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDBSaverServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDBSaverServiceClient struct {
	*kClient
}

func (p *kDBSaverServiceClient) SaveOrder(ctx context.Context, req *db_saver_service.SaveOrderRequest, callOptions ...callopt.Option) (r *db_saver_service.SaveOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SaveOrder(ctx, req)
}

func (p *kDBSaverServiceClient) QueryOrder(ctx context.Context, req *db_saver_service.QueryOrderRequest, callOptions ...callopt.Option) (r *db_saver_service.QueryOrderResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryOrder(ctx, req)
}
