// Code generated by Kitex v0.1.4. DO NOT EDIT.

package dbsaverservice

import (
	"github.com/cloudwego/kitex/server"
	"workspace/dbsavergo/kitex_gen/db_saver_service"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler db_saver_service.DBSaverService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
