// Code generated by Kitex v0.1.4. DO NOT EDIT.
package dbsaverservice

import (
	"github.com/cloudwego/kitex/server"
	"workspace/dbsavergo/kitex_gen/db_saver_service"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler db_saver_service.DBSaverService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
